### ISSUE TITLE
Корневая эвристика. Незакончено вступление.

### ISSUE THREAD

**Issue by CrafterKolyan** [algorithmica-org/articles#10]
https://github.com/algorithmica-org/articles/blob/master/src/ru/sqrt.md

Вторая строчка -> `Корневая эвристика — обобщённое название методов и структур данных, опирающихся`

Опирающихся на что? Явно здесь какая-то проблема.

**Comment by sslotin** [comment]
Дописал. Да, надо бы вообще убрать из доступных с главной страницы статей недописанные части.
