### ISSUE TITLE
Поломанная картинка.  

### ISSUE THREAD

**Issue by iamandrii** [algorithmica-org/articles#25]
Статья: https://algorithmica.org/ru/fenwick
Картинка: https://algorithmica.org/ru/img/fenwick_ranges.png

**Comment by sslotin** [comment]
Спасибо за замечание. При переезде секций на отдельные репозитории картинки переехали, а билд-скрипт, который их копирует, остался старым. Вроде https://github.com/algorithmica-org/articles/commit/8361c3689b6113f400aca23ec7833a91ac44d1ef должен это пофиксить.
